# config.yaml
url: https://api.testnet.paradex.trade/v1
pairs:
  - paradex_symbol: BTC-USD-PERP  #代币种类
    edgex_symbol: 10000001  #代币种类
    paradex_leverage: 20  #杠杆倍数
    edgex_leverage: 20    #杠杆倍数
    base_amount: 100     # 基础交易金额(USD)
    max_price_deviation: 1  #差价金额

  - paradex_symbol: ETH-USD-PERP #代币种类
    paradex_leverage: 20  #杠杆倍数
    base_amount: 100      # 基础交易金额(USD)
    max_price_deviation: 0 #差价金额

execution:
  total_rounds: 100 #刷量次数
  intra_round_delay: [5, 10]  # 秒
  inter_round_delay: [20, 100] # 秒

accounts:
  paradex_1:
    PARADEX_ADDRESS: "test1"
    PARADEX_ACCOUNT_PRIVATE_KEY: "ek1"
  paradex_2:
    PARADEX_ADDRESS: "test2"
    PARADEX_ACCOUNT_PRIVATE_KEY: "ek2"
  paradex_3:
    PARADEX_ADDRESS: "tes3"
    PARADEX_ACCOUNT_PRIVATE_KEY: "ek3"
  paradex_4:
    PARADEX_ADDRESS: "tes4"
    PARADEX_ACCOUNT_PRIVATE_KEY: "ek4"